services:
  rust-rsa-replacer:
    container_name: rust-rsa-replacer
    build: .
    volumes:
      - .:/rust/rsa-replacer
    command: cargo run
    tty: true
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 8080:8080
